### ISSUE TITLE
The requestAnimationFrame bug on iOS 6

### ISSUE THREAD

**Issue by fillefrans** [inma-no/advertsspec#24]
How about this approach: [ronkorving / ios6-timers.js](https://gist.github.com/ronkorving/3755461)

That would seem to fix the iOS 6 problem, if it works. 

RequestAnimationFrame should be brilliant for Gardr, especially if we could do the equivalent of [iframe].contents().find('body').blur() to activate/inactivate animations as creatives become visible and disappear. This would be a huge win for the iframe-approach, I'd say. 

It has the additional advantage of reinstating the requestAnimationFrame API as best practice, which it actually is.

Is there a documented way to reproduce the bug?

**Comment by jackdoyle** [comment]
You might want to look at this: http://greensock.com/css-performance/

**Comment by OleSan** [comment]
I'll remove the limitation that it is not allowed at all with requestAnimationFrame, but will wait to remove that animation is CSS only before user interaction before more tests are done. 

The RAF bug was fixed in iOS 6.1, and our userbase with the old iOS 6.0 is only 0,06% now. It should be safe to remove it now.

**Comment by gadgetgnome** [comment]
@OleSan was it so that JS-animations is allowed from start now?

**Comment by OleSan** [comment]
@gadgetgnome We'll start testing with Greensock today. I don't think we'll allow _all_ JS animation, like using jQuery for animation. But Greensock looks good. Just need to test it on a few older devices in our lab.

**Comment by jackdoyle** [comment]
Let us know if you run into any problems or have questions. http://greensock.com/forums is a great resource too. Oh, and FYI we release a pretty big update (1.18.0) on Monday night but we haven't announced it yet because we're waiting for the CDN to update and we're working on a blog post about the new features. So I'd encourage you to make sure you're using the latest version. :)

**Comment by OleSan** [comment]
Tests good on the test creative from APT even on old android and iphone. I'll add GSAP to the spec unless there is a big complaint before monday 21st of september.
